/* Featured products Home/Admin V37 */
(()=>{const A=id=>document.getElementById(id);const limit=6;
function chosen(){return (cat||[]).filter(x=>x.active!==false&&x.featured&&Number(x.stock_qty)>0).slice(0,limit)}
function paint(){const g=A('homeGrid');if(!g)return;const a=chosen(),fn=typeof proCard==='function'?proCard:card;g.innerHTML=a.length?a.map(fn).join(''):'<div class="homeFeaturedEmptyV37">Nenhum produto em destaque no momento.</div>';const h=document.querySelector('#home .homeV13Section h2');if(h)h.textContent='Produtos em destaque'}
window.paintHomeFeaturedV37=paint;
function adminCount(){return (adm?.products||[]).filter(x=>x.active!==false&&x.featured).length}
function ensureControl(){const box=document.querySelector('#productModal .productEditBox .two');if(!box)return null;let w=A('featuredControlV37');if(!w){w=document.createElement('label');w.id='featuredControlV37';w.className='featuredControlV37 full';w.innerHTML='<input id="pfeaturedV37" type="checkbox"><span class="featuredSwitchV37"></span><span class="featuredControlTextV37"><b>⭐ Exibir em destaque na Home</b><span>Escolha até 6 produtos para aparecer na tela inicial.</span></span><em id="featuredCountV37" class="featuredCountV37"></em>';box.appendChild(w)}const c=A('featuredCountV37');if(c)c.textContent=adminCount()+' de '+limit;return w}
const editBase=window.editProduct;if(typeof editBase==='function')window.editProduct=function(id=''){const r=editBase.apply(this,arguments);setTimeout(()=>{ensureControl();const x=id?(adm?.products||[]).find(p=>p.id===id):null;if(A('pfeaturedV37'))A('pfeaturedV37').checked=!!x?.featured;const c=A('featuredCountV37');if(c)c.textContent=adminCount()+' de '+limit},0);return r};
const saveBase=window.saveProduct;if(typeof saveBase==='function')window.saveProduct=async function(){const ctl=A('pfeaturedV37'),wanted=!!ctl?.checked,id=val('pi'),sku=val('psku'),before=id?(adm?.products||[]).find(x=>x.id===id):null,was=!!before?.featured;if(wanted&&!was&&adminCount()>=limit){toast('Você já escolheu 6 produtos em destaque. Desmarque um antes de adicionar outro.');return}await saveBase.apply(this,arguments);let p=id?(adm?.products||[]).find(x=>x.id===id):(adm?.products||[]).find(x=>String(x.sku||'')===String(sku||''));if(!p||!!p.featured===wanted){paint();return}try{await api('/rest/v1/rpc/admin_set_product_featured_v1',{method:'POST',body:JSON.stringify({p_product_id:p.id,p_featured:wanted})});await Promise.all([loadCat(),loadAdmin()]);paint();toast(wanted?'Produto adicionado aos destaques':'Produto removido dos destaques')}catch(e){const m=String(e?.message||'');toast(m.includes('FEATURED_LIMIT_6')?'Limite de 6 produtos em destaque atingido.':m||'Não foi possível atualizar o destaque')}};
const loadCatBase=window.loadCat;if(typeof loadCatBase==='function')window.loadCat=async function(){const r=await loadCatBase.apply(this,arguments);paint();return r};
const renderAdminBase=window.renderAdmin;if(typeof renderAdminBase==='function')window.renderAdmin=function(){const r=renderAdminBase.apply(this,arguments);const c=A('featuredCountV37');if(c)c.textContent=adminCount()+' de '+limit;return r};
function boot(){paint();if(typeof adm!=='undefined'&&adm?.ok)ensureControl()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,200),{once:true});else setTimeout(boot,200);
})();