/* V29 — recursos profissionais sobre V28 */
let checkoutSettings={},adminSales={},detailProduct=null,detailImage='';
const _cardV28=card,_renderProductsV28=renderProducts,_editProductV28=editProduct,_saveProductV28=saveProduct,_loadAdminV28=loadAdmin,_renderAdminV28=renderAdmin,_adminPageV28=adminPage,_placeOrderV28=placeOrder,_checkoutV28=checkout,_loadCatV28=loadCat;
function tiersOf(x){return (Array.isArray(x?.price_tiers)?x.price_tiers:[]).map(t=>({min:+(t.min??t.min_qty??0),price:+t.price})).filter(t=>t.min>0&&t.price>0).sort((a,b)=>a.min-b.min)}
function unitPrice(x,qty){let price=+x.sale_price||0;for(const t of tiersOf(x))if(qty>=t.min)price=t.price;return price}
function profitData(x,unit=+x.sale_price||0){const ref=+x.reference_price||0;if(ref<=0||ref<=unit)return null;const profit=ref-unit,margin=profit/ref*100;return{ref,profit,margin}}
function hasRealTiers(x){const ts=tiersOf(x);return ts.length>1 || (ts.length===1&&ts[0].min>1)}
function galleryOf(x){return [x?.image_url,...(Array.isArray(x?.gallery_urls)?x.gallery_urls:[])].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)}
function stockLabel(x){return +x.stock_qty>0?`${x.stock_qty} em estoque`:'Sem estoque no momento'}
function proCard(x){const pd=profitData(x),ts=tiersOf(x),out=+x.stock_qty<=0;return `<div class="prod ${out?'stockOut':''}"><div class="img" onclick="openProductDetail('${x.id}')">${x.image_url?`<img loading="lazy" src="${esc(x.image_url)}" alt="${esc(x.name)}">`:'<span style="font-size:30px">📦</span>'}</div><small>${esc(x.brand||x.category_name||'Shop Importadora')} • ${esc(x.sku||'')}</small><h3 onclick="openProductDetail('${x.id}')">${esc(x.name)}</h3><div class="price">${money(x.sale_price)}${x.reference_price?`<span class="oldPrice">${money(x.reference_price)}</span>`:''}</div>${pd?`<div class="marginMini">Lucro potencial ${money(pd.profit)}/un. • ${pd.margin.toFixed(0)}%</div>`:''}<small>${stockLabel(x)}</small>${hasRealTiers(x)?'<div class="tierHint">PREÇO POR QUANTIDADE</div>':''}<div class="prodActions"><button class="btn" onclick="openProductDetail('${x.id}')">Ver detalhes</button><button class="btn red" onclick="quickAdd('${x.id}')" ${out?'disabled':''}>Adicionar</button></div></div>`}
card=proCard;
window.quickAdd=function(id){const x=cat.find(p=>p.id===id);if(!x||+x.stock_qty<=0)return toast('Produto sem estoque');const q=Math.max(+x.min_per_customer||1,1);cart[id]=(cart[id]||0)+q;if(cart[id]>+x.stock_qty)cart[id]=+x.stock_qty;localStorage.setItem(CK,JSON.stringify(cart));renderCart();toast('Produto adicionado')};
function fillFilters(){if(!$('brandFilter')||!$('categoryFilter'))return;const b=[...new Set(cat.map(x=>x.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),c=[...new Map(cat.filter(x=>x.category_id).map(x=>[x.category_id,x.category_name||'Categoria'])).entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),'pt-BR'));const bv=$('brandFilter').value,cv=$('categoryFilter').value;$('brandFilter').innerHTML='<option value="">Todas as marcas</option>'+b.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('categoryFilter').innerHTML='<option value="">Todas as categorias</option>'+c.map(([id,n])=>`<option value="${id}">${esc(n)}</option>`).join('');if(b.includes(bv))$('brandFilter').value=bv;if(c.some(x=>x[0]===cv))$('categoryFilter').value=cv}
renderProducts=function(){let a=[...cat],q=$('q')?.value.toLowerCase().trim()||'',so=$('sort')?.value||'featured',brand=$('brandFilter')?.value||'',category=$('categoryFilter')?.value||'';if(q)a=a.filter(x=>`${x.name} ${x.brand||''} ${x.sku||''} ${x.category_name||''}`.toLowerCase().includes(q));if(brand)a=a.filter(x=>x.brand===brand);if(category)a=a.filter(x=>String(x.category_id)===category);if(so==='low')a.sort((a,b)=>a.sale_price-b.sale_price);else if(so==='high')a.sort((a,b)=>b.sale_price-a.sale_price);else if(so==='stock')a.sort((a,b)=>b.stock_qty-a.stock_qty);else if(so==='sold')a.sort((a,b)=>(b.sold_qty||0)-(a.sold_qty||0));else if(so==='margin')a.sort((a,b)=>(profitData(b)?.margin||0)-(profitData(a)?.margin||0));else a.sort((a,b)=>(b.featured?1:0)-(a.featured?1:0)||(b.sold_qty||0)-(a.sold_qty||0));$('products').innerHTML=a.map(proCard).join('')||'<div class="mut">Nenhum produto encontrado.</div>';if($('catalogCount'))$('catalogCount').textContent=`${a.length} produto${a.length===1?'':'s'}`}
loadCat=async function(){await _loadCatV28();fillFilters();if($('homeGrid'))$('homeGrid').innerHTML=cat.filter(x=>+x.stock_qty>0).slice(0,4).map(proCard).join('');renderProducts()}
window.openProductDetail=function(id){const x=cat.find(p=>p.id===id);if(!x)return;detailProduct=x;const imgs=galleryOf(x);detailImage=imgs[0]||'';$('detailName').textContent=x.name;$('detailKicker').textContent=(x.category_name||'PRODUTO').toUpperCase();$('detailMeta').textContent=[x.brand,x.sku&&`SKU ${x.sku}`].filter(Boolean).join(' • ');renderDetailImage();$('detailGallery').innerHTML=imgs.map((u,i)=>`<button class="detailThumb" onclick="setDetailImage('${encodeURIComponent(u)}')"><img src="${esc(u)}" alt="Foto ${i+1}"></button>`).join('');const qty=Math.max(+x.min_per_customer||1,1);$('detailQty').value=qty;$('detailQty').min=qty;$('detailQty').max=+x.stock_qty||qty;const pd=profitData(x);$('detailProfit').innerHTML=pd?`<b>Potencial de revenda: ${money(pd.profit)} de lucro por unidade</b><small>Venda sugerida ${money(pd.ref)} • margem potencial ${pd.margin.toFixed(0)}%. Valor sugerido, ajuste conforme seu mercado.</small>`:'<small>Cadastre o preço de venda sugerido para mostrar a margem ao lojista.</small>';const ts=tiersOf(x);$('detailTiers').innerHTML=ts.length?`<div class="mut">PREÇO POR QUANTIDADE</div>`+ts.map(t=>`<div class="detailTier" data-min="${t.min}"><span>A partir de <b>${t.min} un.</b></span><b>${money(t.price)}/un.</b></div>`).join(''):`<div class="detailTier"><span>Preço de atacado</span><b>${money(x.sale_price)}/un.</b></div>`;$('detailStock').innerHTML=`<b>${stockLabel(x)}</b>${x.warranty_text?` • Garantia: ${esc(x.warranty_text)}`:''}`;$('detailDescription').innerHTML=x.description?`<h3>Descrição</h3><p>${esc(x.description).replace(/\n/g,'<br>')}</p>`:'';const sp=x.specs&&typeof x.specs==='object'?Object.entries(x.specs):[];$('detailSpecs').innerHTML=sp.length?`<h3>Especificações</h3><div class="specGrid">${sp.map(([k,v])=>`<div class="specItem"><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div>`:'';updateDetailPrice();$('productDetailModal').classList.add('on')}
window.setDetailImage=function(u){detailImage=decodeURIComponent(u);renderDetailImage()};function renderDetailImage(){$('detailMainImage').innerHTML=detailImage?`<img src="${esc(detailImage)}" alt="${esc(detailProduct?.name||'Produto')}">`:'<span style="font-size:55px">📦</span>'}
window.updateDetailPrice=function(){if(!detailProduct)return;let q=Math.max(+$('detailQty').value||1,+detailProduct.min_per_customer||1),u=unitPrice(detailProduct,q),pd=profitData(detailProduct,u);$('detailPrice').innerHTML=`<strong>${money(u)} <small>/ unidade</small></strong>${q>1?`<small>${q} unidades = ${money(u*q)}</small>`:''}`;document.querySelectorAll('#detailTiers .detailTier').forEach(el=>el.classList.toggle('on',q>=+el.dataset.min&&+el.dataset.min===Math.max(...tiersOf(detailProduct).filter(t=>q>=t.min).map(t=>t.min),0)));if(pd)$('detailProfit').innerHTML=`<b>Lucro potencial ${money(pd.profit)}/un. • margem ${pd.margin.toFixed(0)}%</b><small>Venda sugerida ${money(pd.ref)}. O valor de revenda é uma referência comercial.</small>`}
window.addFromDetail=function(){if(!detailProduct)return;const q=Math.max(+$('detailQty').value||1,+detailProduct.min_per_customer||1);if(q>+detailProduct.stock_qty)return toast('Quantidade maior que o estoque disponível');cart[detailProduct.id]=q;localStorage.setItem(CK,JSON.stringify(cart));renderCart();closeM('productDetailModal');toast(`Adicionado por ${money(unitPrice(detailProduct,q))}/un.`)};

async function loadCheckoutSettings(){try{let d=await api('/rest/v1/rpc/get_checkout_settings_v1',{method:'POST',body:'{}'});checkoutSettings=Array.isArray(d)?d[0]||{}:d||{}}catch(e){console.warn('checkout settings',e.message);checkoutSettings={}}}
async function refreshCheckoutQuote(){if(!$('checkoutQuote'))return;const items=Object.entries(cart).map(([product_id,quantity])=>({product_id,quantity:+quantity}));if(!items.length){$('checkoutQuote').innerHTML='';return}try{$('checkoutQuote').innerHTML='<div class="mut">Calculando pedido...</div>';const q=await api('/rest/v1/rpc/quote_shop_cart_v1',{method:'POST',body:JSON.stringify({p_shipping_method:$('cm')?.value||'pickup',p_items:items})});$('checkoutQuote').innerHTML=`<div class="quoteRow"><span>Produtos</span><b>${money(q.subtotal)}</b></div><div class="quoteRow"><span>Frete</span><b>${+q.freight?money(q.freight):'Grátis / retirada'}</b></div><div class="quoteRow total"><span>Total</span><b>${money(q.total)}</b></div>${!q.meets_minimum?`<div class="quoteNotice">Pedido mínimo: ${money(q.minimum_order)}</div>`:''}${+q.free_shipping_threshold>0&&$('cm')?.value==='carrier'?`<div class="mut">Frete grátis acima de ${money(q.free_shipping_threshold)}</div>`:''}`;$('confirmOrderBtn').disabled=!q.meets_minimum}catch(e){$('checkoutQuote').innerHTML=`<div class="quoteNotice">${esc(e.message)}</div>`;$('confirmOrderBtn').disabled=true}}
window.refreshCheckoutQuote=refreshCheckoutQuote;
checkout=function(){_checkoutV28();populateAddressSelect();checkoutShippingChanged();refreshCheckoutQuote()};
window.checkoutShippingChanged=function(){if(!$('cm'))return;const carrier=$('cm').value==='carrier';if($('caSel'))$('caSel').classList.toggle('hide',!carrier);if(carrier){populateAddressSelect();const d=deliveryAddresses.find(a=>a.id===$('caSel')?.value)||deliveryAddresses.find(a=>a.is_default);if(d){$('caSel').value=d.id;useSavedAddress(d.id)}}refreshCheckoutQuote()};
async function lookupCep(cep,targets){const clean=String(cep||'').replace(/\D/g,'');if(clean.length!==8)return;try{const r=await fetch(`https://viacep.com.br/ws/${clean}/json/`);const d=await r.json();if(d.erro)return;setv(targets.street,d.logradouro);setv(targets.district,d.bairro);setv(targets.city,d.localidade);setv(targets.state,d.uf)}catch{}}
window.lookupCep=lookupCep;
document.addEventListener('blur',e=>{if(e.target?.id==='cc')lookupCep(e.target.value,{street:'ct',district:'cbairro',city:'cci',state:'cu'});if(e.target?.id==='bfCep')lookupCep(e.target.value,{street:'bfStreet',district:'bfDistrict',city:'bfCity',state:'bfState'});if(e.target?.id==='addrCep')lookupCep(e.target.value,{street:'addrStreet',district:'addrDistrict',city:'addrCity',state:'addrState'})},true);
